### ISSUE TITLE
ios: error = type 'Future<dynamic>' is not a subtype of type 'FutureOr<String>' in type cast

### ISSUE THREAD

**Issue by otopba** [adaptyteam/AdaptySDK-Flutter#36]
On iOS an error when trying to make a pending purchase:

```
type 'Future<dynamic>' is not a subtype of type 'FutureOr<String>' in type cast
#0      Adapty.makeDeferredPurchase (package:adapty_flutter/adapty_flutter.dart:211)
#1      AdaptyPurchaseService.makeDeferredPurchase (package:word_daily/services/purchase/adapty_purchase_service.dart:376)
```

**Comment by x401om** [comment]
fixed in 1.0.14
